-- Gestão de Concursos IFBA: execute este arquivo no SQL Editor do Supabase.
create extension if not exists pgcrypto;
create type public.perfil_usuario as enum ('administrador','operador','leitor');
create type public.tipo_concurso as enum ('docente','tae');
create type public.modalidade_cota as enum ('ac','pp','pcd');
create type public.status_lista as enum ('numero_de_vagas','lista_de_espera');
create type public.status_admissao as enum ('aguardando_convocacao','aceitou_convocacao','entregou_documentacao','realizou_pericia','nomeado_diario_oficial','tomou_posse','entrou_em_exercicio','pediu_final_de_fila','desistente');
create type public.origem_vaga as enum ('vaga_nova','vacancia','aposentadoria','exoneracao','redistribuicao','remocao_recomposicao','outra');
create type public.status_demanda as enum ('aberta','em_convocacao','parcialmente_atendida','atendida','cancelada');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,nome text not null,perfil public.perfil_usuario not null default 'leitor',ativo boolean not null default true,created_at timestamptz default now());
create table public.campi(id uuid primary key default gen_random_uuid(),nome text not null unique,sigla text unique,ativo boolean not null default true);
create table public.concursos(id uuid primary key default gen_random_uuid(),nome text not null,tipo public.tipo_concurso not null,edital text,validade_inicio date,validade_fim date,ativo boolean not null default true);
create table public.areas_cargos(id uuid primary key default gen_random_uuid(),concurso_id uuid not null references public.concursos(id),nome text not null,codigo text,unique(concurso_id,nome));
create table public.candidatos(id uuid primary key default gen_random_uuid(),concurso_id uuid not null references public.concursos(id),area_cargo_id uuid not null references public.areas_cargos(id),nome text not null,cpf text not null,email text,telefone text,modalidade public.modalidade_cota not null,classificacao_geral int not null check(classificacao_geral>0),classificacao_cota int not null check(classificacao_cota>0),posicao_atual int not null check(posicao_atual>0),situacao_lista public.status_lista not null,status_atual public.status_admissao not null default 'aguardando_convocacao',ativo boolean not null default true,created_at timestamptz default now(),updated_at timestamptz default now(),unique(concurso_id,cpf),unique(concurso_id,area_cargo_id,modalidade,posicao_atual));
create table public.importacoes_listas(id uuid primary key default gen_random_uuid(),concurso_id uuid not null references public.concursos(id),arquivo_nome text not null,arquivo_path text,total_linhas int default 0,linhas_importadas int default 0,linhas_com_erro int default 0,importado_por uuid references public.profiles(id),created_at timestamptz default now());
create table public.demandas(id uuid primary key default gen_random_uuid(),numero text not null unique,concurso_id uuid not null references public.concursos(id),area_cargo_id uuid not null references public.areas_cargos(id),origem public.origem_vaga not null,origem_descricao text,processo_sei text,justificativa text,situacao public.status_demanda not null default 'aberta',criada_por uuid references public.profiles(id),created_at timestamptz default now(),updated_at timestamptz default now());
create table public.demanda_campi(demanda_id uuid references public.demandas(id) on delete cascade,campus_id uuid references public.campi(id),primary key(demanda_id,campus_id));
create table public.itens_demanda(id uuid primary key default gen_random_uuid(),demanda_id uuid not null references public.demandas(id) on delete cascade,modalidade public.modalidade_cota not null,quantidade int not null check(quantidade>0),unique(demanda_id,modalidade));
create table public.convocacoes(id uuid primary key default gen_random_uuid(),item_demanda_id uuid not null references public.itens_demanda(id),candidato_id uuid not null references public.candidatos(id),ativa boolean not null default true,convocado_em timestamptz default now(),registrado_por uuid references public.profiles(id),observacao text);
create unique index uma_convocacao_ativa_por_candidato on public.convocacoes(candidato_id) where ativa;
create table public.movimentacoes_candidato(id uuid primary key default gen_random_uuid(),candidato_id uuid not null references public.candidatos(id),convocacao_id uuid references public.convocacoes(id),status public.status_admissao not null,observacao text,registrado_por uuid references public.profiles(id),created_at timestamptz default now());
create table public.nomeacoes_dou(id uuid primary key default gen_random_uuid(),convocacao_id uuid not null unique references public.convocacoes(id),campus_id uuid not null references public.campi(id),numero_dou text,secao_dou text,data_publicacao date not null,arquivo_path text not null,registrado_por uuid references public.profiles(id),created_at timestamptz default now());

-- A próxima convocação é sempre o primeiro elegível da mesma área/cargo e cota.
create or replace function public.proximo_elegivel(p_item uuid) returns table(candidato_id uuid,nome text,posicao_atual int) language sql stable as $$
 select c.id,c.nome,c.posicao_atual from public.itens_demanda i join public.demandas d on d.id=i.demanda_id join public.candidatos c on c.concurso_id=d.concurso_id and c.area_cargo_id=d.area_cargo_id and c.modalidade=i.modalidade where i.id=p_item and c.ativo and c.status_atual in ('aguardando_convocacao','pediu_final_de_fila') and not exists(select 1 from public.convocacoes v where v.candidato_id=c.id and v.ativa) and not exists(select 1 from public.nomeacoes_dou n join public.convocacoes v on v.id=n.convocacao_id where v.candidato_id=c.id) order by c.posicao_atual limit 1; $$;
create or replace function public.validar_ordem_convocacao() returns trigger language plpgsql as $$ declare p uuid; begin select candidato_id into p from public.proximo_elegivel(new.item_demanda_id); if p is null or p<>new.candidato_id then raise exception 'A convocação deve obedecer ao primeiro candidato elegível.'; end if; return new; end; $$;
create trigger validar_ordem before insert on public.convocacoes for each row execute function public.validar_ordem_convocacao();
-- O campus definitivo da nomeação precisa constar entre os campi previstos na demanda.
create or replace function public.validar_campus_nomeacao() returns trigger language plpgsql as $$ begin if not exists(select 1 from public.convocacoes v join public.itens_demanda i on i.id=v.item_demanda_id join public.demanda_campi dc on dc.demanda_id=i.demanda_id where v.id=new.convocacao_id and dc.campus_id=new.campus_id) then raise exception 'O campus da nomeação deve estar previsto na demanda.'; end if; return new; end; $$;
create trigger validar_campus_nomeacao before insert or update on public.nomeacoes_dou for each row execute function public.validar_campus_nomeacao();
create or replace function public.aplicar_final_de_fila(p_candidato uuid,p_usuario uuid,p_observacao text default null) returns void language plpgsql security definer set search_path=public as $$ declare u int; begin select coalesce(max(posicao_atual),0)+1 into u from candidatos c where (c.concurso_id,c.area_cargo_id,c.modalidade)=(select concurso_id,area_cargo_id,modalidade from candidatos where id=p_candidato); update candidatos set posicao_atual=u,status_atual='pediu_final_de_fila',updated_at=now() where id=p_candidato; update convocacoes set ativa=false where candidato_id=p_candidato and ativa; insert into movimentacoes_candidato(candidato_id,status,observacao,registrado_por) values(p_candidato,'pediu_final_de_fila',p_observacao,p_usuario); end; $$;

-- Visões para alimentar os cards e rankings do painel.
create view public.vw_indicadores_painel as select count(*) filter(where status_atual not in ('aguardando_convocacao','pediu_final_de_fila','desistente')) as convocados,count(*) filter(where status_atual='desistente') as desistentes,count(*) filter(where status_atual in ('aguardando_convocacao','pediu_final_de_fila')) as aguardando_convocacao,count(*) filter(where status_atual='nomeado_diario_oficial') as nomeados_dou from public.candidatos;
create view public.vw_ranking_campi as select ca.nome as campus,count(*) filter(where m.status not in ('aguardando_convocacao','pediu_final_de_fila','desistente')) as convocados,count(*) filter(where m.status='desistente') as desistentes,count(*) filter(where m.status='entrou_em_exercicio') as em_exercicio from public.campi ca left join public.nomeacoes_dou n on n.campus_id=ca.id left join public.convocacoes v on v.id=n.convocacao_id left join public.movimentacoes_candidato m on m.convocacao_id=v.id group by ca.id,ca.nome;

-- RLS: ative antes de liberar o sistema ao público autenticado.
alter table public.profiles enable row level security; alter table public.campi enable row level security; alter table public.concursos enable row level security; alter table public.areas_cargos enable row level security; alter table public.candidatos enable row level security; alter table public.importacoes_listas enable row level security; alter table public.demandas enable row level security; alter table public.demanda_campi enable row level security; alter table public.itens_demanda enable row level security; alter table public.convocacoes enable row level security; alter table public.movimentacoes_candidato enable row level security; alter table public.nomeacoes_dou enable row level security;
create or replace function public.meu_perfil() returns public.perfil_usuario language sql stable security definer set search_path=public as $$select perfil from public.profiles where id=auth.uid() and ativo$$;
create policy "leitura candidatos" on public.candidatos for select to authenticated using(true); create policy "leitura demandas" on public.demandas for select to authenticated using(true); create policy "leitura convocacoes" on public.convocacoes for select to authenticated using(true); create policy "leitura historico" on public.movimentacoes_candidato for select to authenticated using(true); create policy "leitura nomeacoes" on public.nomeacoes_dou for select to authenticated using(true); create policy "leitura parametros campi" on public.campi for select to authenticated using(true); create policy "leitura parametros concursos" on public.concursos for select to authenticated using(true); create policy "leitura parametros areas" on public.areas_cargos for select to authenticated using(true);
create policy "leitura itens demanda" on public.itens_demanda for select to authenticated using(true); create policy "leitura campi demanda" on public.demanda_campi for select to authenticated using(true);
create policy "admin candidatos" on public.candidatos for all to authenticated using(meu_perfil()='administrador') with check(meu_perfil()='administrador'); create policy "admin demandas" on public.demandas for all to authenticated using(meu_perfil()='administrador') with check(meu_perfil()='administrador'); create policy "admin itens" on public.itens_demanda for all to authenticated using(meu_perfil()='administrador') with check(meu_perfil()='administrador'); create policy "operacao convocacoes" on public.convocacoes for all to authenticated using(meu_perfil() in ('administrador','operador')) with check(meu_perfil() in ('administrador','operador')); create policy "operacao historico" on public.movimentacoes_candidato for insert to authenticated with check(meu_perfil() in ('administrador','operador')); create policy "operacao nomeacoes" on public.nomeacoes_dou for all to authenticated using(meu_perfil() in ('administrador','operador')) with check(meu_perfil() in ('administrador','operador'));
