/* Base alinhada à aba Listas. Substitua pela API do Google Sheets em produção. */
window.IFBA_DEMO_DATA={
  atualizadoEm:"2026-08-25T19:30:00-03:00",
  listas:{
    nivel:["Superior - Licenciatura","EPTNM - Concomitante","Superior - Bacharelado","Superior - Tecnologia","EPTNM - Integrado","EPTNM - Subsequente","EPTNM - EJA"],
    modalidade:["Presencial","A distância"],
    tipo_demanda:["Implantação de curso","Reformulação do PPC","Alteração Menor Relevância do PPC","Supensão da oferta","Estudo de viabilidade"],
    etapa_atual:["Mapeamento inicial","Elaboração pelo campus","Análise técnica PROEN","Solicitação ajustes ao campus","Aguardando CONSEPE","Relatado no CONSEPE","Resolução emitida"],
    responsavel_atual:["Campus","PROEN - DPE","PROEN - DESUP","PROEN - DETEC","PROEX - Curricularização","CONSEPE"],
    situacao_consepe:["Não encaminhado","Na Camara de Ensino","Em análise pelo relator","Pauta agendada","Aprovado","Aprovado com Ressalvas - (com a unidade)","Aguardando emissão de Resolução","Resolução Emitida"],
    prioridade:["Alta","Média","Baixa"],
    campus:["Barreiras","Brumado","Camaçari","Cajazeiras","Campo Formoso","Euclides da Cunha","Eunápolis","Feira de Santana","Ilhéus","Irecê","Itabuna","Jacobina","Jaguaquara","Jequié","Juazeiro","Lauro de Freitas","Macaúbas","Paulo Afonso","Poções","Porto Seguro","Salvador","Santo Amaro","Santo Antônio de Jesus","Seabra","Simões Filho","Ubaitaba","Valença","Vitória da Conquista"]
  },
  data:[
    {id:"C001",campus:"Barreiras",curso:"Engenharia Elétrica",nivel:"EPTNM - Concomitante",modalidade:"Presencial",tipo_demanda:"Implantação de curso",etapa_atual:"Solicitação ajustes ao campus",responsavel_atual:"Campus",processo_sei:"00000.000001/2026-00 · DEMO",portaria_comissao:"Portaria nº 001/2026 · DEMO",data_portaria:"2026-02-10",entrada_proen:"2026-06-18",saida_proen:"2026-07-04",entrada_campus:"2026-07-05",saida_campus:"",situacao_consepe:"Não encaminhado",data_consepe:"",prazo:"2026-08-18",prioridade:"Alta",progresso:48,observacoes:"Adequações relativas à curricularização da extensão e à oferta parcial de carga horária a distância."},
    {id:"C002",campus:"Brumado",curso:"Tecnologia em Análise e Desenvolvimento de Sistemas",nivel:"Superior - Licenciatura",modalidade:"Presencial",tipo_demanda:"Implantação de curso",etapa_atual:"Análise técnica PROEN",responsavel_atual:"PROEN",processo_sei:"00000.000002/2026-00 · DEMO",portaria_comissao:"Portaria nº 014/2026 · DEMO",data_portaria:"2026-03-14",entrada_proen:"2026-08-11",saida_proen:"",entrada_campus:"2026-04-03",saida_campus:"2026-08-08",situacao_consepe:"Não encaminhado",data_consepe:"",prazo:"2026-09-05",prioridade:"Alta",progresso:67,observacoes:"Projeto em análise técnica após conclusão do estudo de viabilidade pelo campus."},
    {id:"C003",campus:"Barreiras",curso:"Licenciatura Intercultural Indígena",nivel:"Superior - Bacharelado",modalidade:"Presencial",tipo_demanda:"Implantação de curso",etapa_atual:"Aguardando CONSEPE",responsavel_atual:"CONSEPE",processo_sei:"00000.000003/2026-00 · DEMO",portaria_comissao:"Portaria nº 021/2026 · DEMO",data_portaria:"2026-01-26",entrada_proen:"2026-07-10",saida_proen:"2026-07-20",entrada_campus:"2026-05-05",saida_campus:"2026-07-08",situacao_consepe:"Pauta agendada",data_consepe:"2026-08-21",prazo:"2026-08-21",prioridade:"Alta",progresso:89,observacoes:"Manifestação técnica concluída; projeto encaminhado para apreciação colegiada."},
    {id:"C004",campus:"Brumado",curso:"Engenharia Civil",nivel:"Superior - Tecnologia",modalidade:"Presencial",tipo_demanda:"Atualização do PPC",etapa_atual:"Elaboração pelo campus",responsavel_atual:"Campus",processo_sei:"00000.000004/2026-00 · DEMO",portaria_comissao:"Portaria nº 033/2026 · DEMO",data_portaria:"2026-04-09",entrada_proen:"",saida_proen:"",entrada_campus:"2026-04-11",saida_campus:"",situacao_consepe:"Não encaminhado",data_consepe:"",prazo:"2026-10-15",prioridade:"Média",progresso:31,observacoes:"Revisão do perfil do egresso, matriz curricular e informações regulatórias do curso."},
    {id:"C005",campus:"Juazeiro",curso:"Tecnologia em Logística",nivel:"Superior - Licenciatura",modalidade:"Presencial",tipo_demanda:"Reconhecimento de curso",etapa_atual:"Análise técnica PROEN",responsavel_atual:"PROEN",processo_sei:"00000.000005/2026-00 · DEMO",portaria_comissao:"Portaria nº 042/2026 · DEMO",data_portaria:"2026-05-02",entrada_proen:"2026-08-17",saida_proen:"",entrada_campus:"2026-06-01",saida_campus:"2026-08-14",situacao_consepe:"Não encaminhado",data_consepe:"",prazo:"2026-09-12",prioridade:"Alta",progresso:61,observacoes:"Acompanhamento das adequações necessárias ao processo regulatório de reconhecimento."},
    {id:"C006",campus:"Jaguaquara",curso:"Licenciatura em Letras Português/Libras",nivel:"Superior - Licenciatura",modalidade:"Presencial",tipo_demanda:"Implantação de curso",etapa_atual:"Elaboração pelo campus",responsavel_atual:"Campus",processo_sei:"00000.000006/2026-00 · DEMO",portaria_comissao:"Portaria nº 049/2026 · DEMO",data_portaria:"2026-05-19",entrada_proen:"2026-06-03",saida_proen:"2026-06-12",entrada_campus:"2026-06-14",saida_campus:"",situacao_consepe:"Não encaminhado",data_consepe:"",prazo:"2026-10-30",prioridade:"Média",progresso:38,observacoes:"Construção do projeto com apoio de avaliação técnica externa especializada."},
    {id:"C007",campus:"Euclides da Cunha",curso:"Técnico em Informática Integrado",nivel:"EPTNM - Integrado",modalidade:"Presencial",tipo_demanda:"Reformulação do PPC",etapa_atual:"Mapeamento inicial",responsavel_atual:"Campus",processo_sei:"00000.000007/2026-00 · DEMO",portaria_comissao:"A constituir",data_portaria:"",entrada_proen:"",saida_proen:"",entrada_campus:"2026-08-04",saida_campus:"",situacao_consepe:"Não encaminhado",data_consepe:"",prazo:"2026-11-28",prioridade:"Média",progresso:14,observacoes:"Levantamento inicial para alinhamento ao currículo de referência institucional."},
    {id:"C008",campus:"Lauro de Freitas",curso:"Tecnologia em Jogos Digitais",nivel:"Superior - Tecnologia",modalidade:"Presencial",tipo_demanda:"Atualização do PPC",etapa_atual:"Resolução emitida",responsavel_atual:"PROEN",processo_sei:"00000.000008/2026-00 · DEMO",portaria_comissao:"Portaria nº 058/2026 · DEMO",data_portaria:"2026-02-18",entrada_proen:"2026-07-02",saida_proen:"2026-07-19",entrada_campus:"2026-04-12",saida_campus:"2026-06-28",situacao_consepe:"Aprovado",data_consepe:"2026-07-24",prazo:"2026-07-24",prioridade:"Baixa",progresso:100,observacoes:"Tramitação concluída e aprovação registrada para atualização dos sistemas acadêmicos."},
    {id:"C009",campus:"Irecê",curso:"Engenharia Mecânica",nivel:"Superior - Bacharelado",modalidade:"Presencial",tipo_demanda:"Implantação de curso",etapa_atual:"Solicitação ajustes ao campus",responsavel_atual:"Campus",processo_sei:"00000.000009/2026-00 · DEMO",portaria_comissao:"Portaria nº 063/2026 · DEMO",data_portaria:"2026-03-07",entrada_proen:"2026-07-21",saida_proen:"2026-08-01",entrada_campus:"2026-08-02",saida_campus:"",situacao_consepe:"Não encaminhado",data_consepe:"",prazo:"2026-09-01",prioridade:"Alta",progresso:45,observacoes:"Campus deverá complementar informações de infraestrutura, corpo docente e matriz curricular."},
    {id:"C010",campus:"Porto Seguro",curso:"Técnico em Hospedagem Integrado",nivel:"EPTNM - Integrado",modalidade:"Presencial",tipo_demanda:"Reformulação do PPC",etapa_atual:"Aguardando CONSEPE",responsavel_atual:"CONSEPE",processo_sei:"00000.000010/2026-00 · DEMO",portaria_comissao:"Portaria nº 071/2026 · DEMO",data_portaria:"2026-01-15",entrada_proen:"2026-06-23",saida_proen:"2026-07-07",entrada_campus:"2026-04-20",saida_campus:"2026-06-20",situacao_consepe:"Em análise pelo relator",data_consepe:"2026-08-08",prazo:"2026-09-20",prioridade:"Média",progresso:82,observacoes:"Projeto aguardando designação de relatoria no CONSEPE."}
  ]
};
